#%RAML 1.0
---
title: Swamp backend

/register:
  get:
    description: Renders the register page
  post:
    description: Create a user on the database
    queryParameters:
      username:
        displayName: Username
        type: string
        description: Must be alpha-numeric
        required: true
      email:
        displayName: Email
        type: string
        description: must contain the postfix "@mail.sfsu.edu"
        required: true
      password:
        displayName: Password
        type: string
        description:
        required: true
    responses:
      200:
        description: User successfully added to database
        body:
          application/json:
            example: |
              {
                "success": true,
              }
      400:
        description: Failed to add user to database
        body:
          application/json:
            example: |
              {
                "success": false,
                "reason": "email already exists"
              }

/approve:
  get:
    description: Renders the approve page
  post:
    description: Approve media on the database
    queryParameters:
      m_id:
        displayName: m_id
        type: int
        description: media primary key
        required: true
      admin_id:
        displayName: admin_id
        type: int
        description: id of the admin who approved the listing
        required: true
    responses:
      200:
        description: Media successfully approved
        body:
          application/json:
            example: |
              {
                "success": true,
              }

/reject:
  post:
    description: Reject media on the database
    queryParameters:
      m_id:
        displayName: m_id
        type: int
        description: media primary key
        required: true
      admin_id:
        displayName: admin_id
        type: int
        desciption: id of the admin who rejected the listing
        required: true
    responses:
      200:
        description: Media successfully rejected
        body:
          application/json:
            example: |
              {
                "success": true,
              }

/ban:
  get:
    description: Renders the ban page
  post:
    description: Ban a user on the database
    queryParameters:
      username:
        displayName: Username
        type: string
        description:
        required: true
    responses:
      200:
        description: User successfully banned
        body:
          application/json:
            example: |
              {
                "success": true,
              }
      400:
        description: Failed to ban user
        body:
          application/json:
            example: |
              {
                "success": false,
              }

/browse:
  get:
    description: Renders the browse page
  post:
    description: Get the first 25 accepted media from the given category
    queryParameters:
      category:
        displayName: Category
        type: string
        description: can be "all", "document", "image", "video", or "audio"
        required: true
      search:
        displayName: Search
        type: string
        description: used to find media with a specific title/description
        required: true
    responses:
      200:
        description: Media successfully fetched
        body:
          application/json:
            example: |
              {
                "success": true,
                "category":"audio",
                "results": 
                [
                  {
                    "id":31,
                    "author_id":25,
                    "title":"My Music File",
                    "description":"This is an audio file from my class",
                    "preview_path":"default/audio.png",
                    "raw_path":"raw/2020-03-07:3.cu",
                    "category":"audio",
                    "status":"approved",
                    "author_username":"william"
                  },
                  {
                    "id":33,
                    "author_id":25,
                    "title":"Test File",
                    "description":"Test Description",
                    "preview_path":"preview/2020-03-10:1.jpg",
                    "raw_path":"raw/2020-03-10:1.jpg",
                    "category":"audio",
                    "status":"approved",
                    "author_username":"kevin"
                  }
                ]
              }

/download:
  post:
    description: Download raw data file
    queryParameters:
      path:
        displayName: Path
        type: string
        description: the relative path of the file from the media directory
        required: true
    responses:
      200:
        description: File be available for download on success

/logout:
  post:
    description: Logout from the website
    responses:
      200:
        description: User has successfully logged out
        body:
          application/json:
            example: |
              {
                "success": true,
              }

/upload:
  post:
    description: Upload file to filesystem and create a logical definition on database
    queryParameters:
      file:
        displayName: File
        type: file
        description: raw data to be uploaded to file system
        required: true
      preview:
        displayName: Preview
        type: file
        description: image preview that will be shown on the store page
        required: false
      title:
        displayName: Title
        type: string
        description:
        required: true
      description:
        displayName: Description
        type: string
        description:
        required: true
      category:
        displayName: Category
        type: string
        description: can be "document", "image", "video", or "audio"
        required: true
    responses:
      200:
        description: Successfully uploaded media
        body:
          application/json:
            example: |
              {
                "success": true,
              }

/login:
  get:
    description: Renders the login page
  post:
    description: Login to the website
    queryParameters:
      username:
        displayName: Username
        type: string
        required: true
      password:
        displayName: Password
        type: string
        required: true
    responses:
      200:
        description: Successfully logged in
        body:
          application/json:
            example: |
              {
                "success": true,
                "user": USER_INFORMATION
              }

/cart:
  get:
    description: Renders media items in your shopping cart
  post:
    description: Adds item to your shopping cart
    queryParameters:
      m_id:
        displayName: m_id
        type: int
        description: media primary key
        required: true
      acc_id:
        displayName: acc_id
        type: int
        description: id of the logged in user
        required: true
    responses:
      200:
        description: Media successfully added to cart
        body:
          application/json:
            example: |
              {
                "success": true,
              }

/listings:
  get:
    description: Renders the listings page
  post:
    description: Get the first 25 media posted from the current user
    queryParameters:
    responses:
      200:
        description: Media successfully fetched
        body:
          application/json:
            example: |
              {
                "success": true,
                "results": 
                [
                  {
                    "id":31,
                    "author_id":25,
                    "title":"My Music File",
                    "description":"This is an audio file from my class",
                    "preview_path":"default/audio.png",
                    "raw_path":"raw/2020-03-07:3.cu",
                    "category":"audio",
                    "status":"approved",
                    "author_username":"william"
                  },
                  {
                    "id":33,
                    "author_id":25,
                    "title":"Test File",
                    "description":"Test Description",
                    "preview_path":"preview/2020-03-10:1.jpg",
                    "raw_path":"raw/2020-03-10:1.jpg",
                    "category":"audio",
                    "status":"approved",
                    "author_username":"kevin"
                  }
                ]
              }

/purchases:
  get:
    description: Renders the purchases page
  post:
    description: Get the first 25 media purchased from the current user
    queryParameters:
    responses:
      200:
        description: Media successfully fetched
        body:
          application/json:
            example: |
              {
                "success": true,
                "results": 
                [
                  {
                    "id":31,
                    "author_id":25,
                    "title":"My Music File",
                    "description":"This is an audio file from my class",
                    "preview_path":"default/audio.png",
                    "raw_path":"raw/2020-03-07:3.cu",
                    "category":"audio",
                    "status":"approved",
                    "author_username":"william"
                  },
                  {
                    "id":33,
                    "author_id":25,
                    "title":"Test File",
                    "description":"Test Description",
                    "preview_path":"preview/2020-03-10:1.jpg",
                    "raw_path":"raw/2020-03-10:1.jpg",
                    "category":"audio",
                    "status":"approved",
                    "author_username":"kevin"
                  }
                ]
              }

/message:
  get:
    description: Renders the message page with textbox form
  post:
    description: Sends message to seller of media listing
    queryParameters:
      sender_id:
        displayName: sender_id
        type: number
        required: true
      receiver_id:
        displayName: receiver_id
        type: number
        required: true
      message:
        displayName: Message
        type: string
        required: true
    responses:
      200:
        description: Message successfully sent
        body:
          application/json:
            example: |
              {
                "success": "true"
              }
      400:
        description: User isn't logged in
        body:
          application/json:
            example: |
              {
                "success": "false"
              }

/messagebox:
  get:
    description: Displays all messages sent to you
    queryParameters:
    reponses:
      200:
        description: Successfully retrieved messages send to you
        body:
          application/json:
            example: |
              {
                "success": true,
                "results": 
                [
                  {
                    "sender_id":5,
                    "acc_id":3,
                    "message":"hello world",
                    "date":"2020-04-28",
                    "time":"01:43:55",
                    "read":0
                  }
                ]
              }